// Generated by scripts/generate-template-profile.mjs. Do not edit by hand.
export const brandThemeProfile = {
  colorTokenProfile: 'crave-orchard',
  fontTokenProfile: 'outfit-figtree',
} as const;

export const colors = {
  "canvas": "#F7EFE6",
  "contentCanvas": "#FFF4E9",
  "surface": "#FFFFFF",
  "surfaceDark": "#3D322E",
  "ink": "#261E1C",
  "accent": "#FC7D00",
  "accentSoft": "#FFAF5F",
  "danger": "#D0442F",
  "border": "#EADCCC",
  "divider": "#EFE3D6",
  "progressTrack": "#F1E5D8",
  "surfaceMuted": "#F4ECE3",
  "imageSurface": "#EAD3BE",
  "textMuted": "#7A695D",
  "textSubtle": "#9C8A7C",
  "iconMuted": "#A9998B",
  "textOnDarkMuted": "#B9A899",
  "heroSupporting": "#E9D6C4",
  "onboardingInactiveDot": "#5C4C42",
  "transparent": "transparent"
} as const;

export const fontFamilies = {
  "bodyRegular": "Figtree_400Regular",
  "bodyMedium": "Figtree_500Medium",
  "bodySemiBold": "Figtree_600SemiBold",
  "bodyBold": "Figtree_700Bold",
  "editorialItalic": "InstrumentSerif_400Regular_Italic",
  "headingSemiBold": "Outfit_600SemiBold",
  "headingBold": "Outfit_700Bold",
  "headingExtraBold": "Outfit_800ExtraBold"
} as const;
