// Generated by scripts/generate-template-profile.mjs. Do not edit by hand.
import { Figtree_400Regular } from '@expo-google-fonts/figtree/400Regular/index.js';
import { Figtree_500Medium } from '@expo-google-fonts/figtree/500Medium/index.js';
import { Figtree_600SemiBold } from '@expo-google-fonts/figtree/600SemiBold/index.js';
import { Figtree_700Bold } from '@expo-google-fonts/figtree/700Bold/index.js';
import { InstrumentSerif_400Regular_Italic } from '@expo-google-fonts/instrument-serif/400Regular_Italic/index.js';
import { Outfit_600SemiBold } from '@expo-google-fonts/outfit/600SemiBold/index.js';
import { Outfit_700Bold } from '@expo-google-fonts/outfit/700Bold/index.js';
import { Outfit_800ExtraBold } from '@expo-google-fonts/outfit/800ExtraBold/index.js';

export const appFonts = {
  Figtree_400Regular,
  Figtree_500Medium,
  Figtree_600SemiBold,
  Figtree_700Bold,
  InstrumentSerif_400Regular_Italic,
  Outfit_600SemiBold,
  Outfit_700Bold,
  Outfit_800ExtraBold,
};
